<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions 
    targetNamespace="https://www.skatteverket.se/folkbokforing/na/personpostXML/v2" 
    xmlns:impl="https://www.skatteverket.se/folkbokforing/na/personpostXML/v2"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
    xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" 
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:na="http://xmls.skatteverket.se/se/skatteverket/folkbokforing/na/epersondata/V1">
   <wsdl:documentation>Version 2.0</wsdl:documentation> 
   <wsdl:types>
       <xsd:schema targetNamespace="https://www.skatteverket.se/folkbokforing/na/personpostXML/v2" xmlns="http://www.w3.org/2001/XMLSchema">
           <xsd:import schemaLocation="http://xmls.skatteverket.se/se/skatteverket/folkbokforing/na/epersondata/V1/Epersondata.xsd" namespace="http://xmls.skatteverket.se/se/skatteverket/folkbokforing/na/epersondata/V1"/>
       </xsd:schema>
   </wsdl:types>
   <wsdl:message name="getDataRequest">
      <wsdl:part name="parameters" element="na:PersonpostRequest"/>
   </wsdl:message>
   <wsdl:message name="getDataResponse">
      <wsdl:part name="parameters" element="na:PersonpostXMLResponse"/>
   </wsdl:message>
   <wsdl:message name="NaWebServiceException">
       <wsdl:part name="fault" element="na:WebServiceFault"/>
   </wsdl:message>
   <wsdl:portType name="PersonpostXMLInterface">
      <wsdl:operation name="getData">
         <wsdl:input message="impl:getDataRequest" name="getDataRequest"/>
         <wsdl:output message="impl:getDataResponse" name="getDataResponse"/>
         <wsdl:fault message="impl:NaWebServiceException" name="NaWebServiceException" />
      </wsdl:operation>
   </wsdl:portType>
   <wsdl:binding name="PersonpostXMLSoapBinding" type="impl:PersonpostXMLInterface">
      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
      <wsdl:operation name="getData">
         <wsdlsoap:operation soapAction=""/>
         <wsdl:input name="getDataRequest">
            <wsdlsoap:body  use="literal" parts="parameters"/>
         </wsdl:input>
         <wsdl:output name="getDataResponse">
            <wsdlsoap:body use="literal" parts="parameters"/>
         </wsdl:output>
         <wsdl:fault name="NaWebServiceException">
            <wsdlsoap:fault name="NaWebServiceException" use="literal"/>
         </wsdl:fault>
      </wsdl:operation>
   </wsdl:binding>
   <wsdl:service name="PersonpostXMLService">
      <wsdl:port binding="impl:PersonpostXMLSoapBinding" name="personpostXML">
         <wsdlsoap:address location="https://www2.skatteverket.se/na/na_epersondata/V2/personpostXML"/>
      </wsdl:port>
   </wsdl:service>
</wsdl:definitions>
